### ISSUE TITLE
Advantages with BBHTTP over AFNetworking

### ISSUE THREAD

**Issue by hfossli** [biasedbit/BBHTTP#15]
Hi!

Could you in the readme say something about the advantages over say AFNetworking? I've read this part.

> Well, unlike NSURLConnection and, consequently, any lib that relies on it, BBHTTP...
> 
>    is strictly compliant with section 8.2.3 of RFC 2616, a.k.a. the misbeloved Expect: 100-Continue header;
>    can receive server error responses midway through upload — as opposed to continuing to pump data into socket eden, and eventually reporting connection timeout instead of the actual error response sent by the server.

And that's good. But I guess there is some other advantages and hidden gems maybe in the syntax and structure of BBHTTP over say AFNetworking?

**Comment by biasedbit** [comment]
Howdy,

The main advantage is mostly just being able to correctly handle error responses midway through uploads &mdash; that's the whole reason why it was built. According to #14, NSURLConnection now handles 100-Continue &mdash; though I still have to experiment with it.

I believe the **Highlights** section on the README covers most of the _gems_ you mention. I chose not to directly compare it with alternatives (like AFNetworking) because BBHTTP is still a long way from their feature set and thus, in my opinion, not directly comparable.

**Comment by hfossli** [comment]
Okay. Thanks for the answer. I understand :)

**Comment by hfossli** [comment]
It looks really sweet by the way!

**Comment by biasedbit** [comment]
Thanks for the feedback and support :)
