### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by jasperblues** [biasedbit/BBHTTP#5]
Show me how to get a plain string as well as Json and image. . . 

I found what I was looking for. Maybe a link to docs for https://github.com/brunodecarvalho/BBHotpotato/blob/master/Classes/BBHTTPRequest%2BConvenience.h

. ... would make it even faster

**Comment by biasedbit** [comment]
There's a comprehensive description on this wiki page: https://github.com/brunodecarvalho/BBHotpotato/wiki/Response-content-handling

I didn't add it to the README as I felt it would be getting into too much detail regarding all the possible parsing options instead of providing a broader scope introduction.

I'm not too keen on adding the plain text processing on the README, do you feel like a link to the Wiki page would suffice?

**Comment by jasperblues** [comment]
Wow plenty of info there. Yes a link to the wiki page would be nice. I just assumed the wiki was empty.
